class CreateAccounts < ActiveRecord::Migration
  def self.up
    create_table :accounts do |t|
      t.string  :name
      t.string  :ancestry
      t.decimal :taverage

      t.timestamps
    end
    
    Account.create(:name=>'Root')
    Account.create(:name=>'Edelar',:ancestry=>'1')
    Account.create(:name=>'Edesa',:ancestry=>'1')
    Account.create(:name=>'Edesal',:ancestry=>'1')
    Account.create(:name=>'Comercial',:ancestry=>'1/2')
    Account.create(:name=>'Gestion de Impagados',:ancestry=>'1/2')
    Account.create(:name=>'Gestion de Perdidas',:ancestry=>'1/2')
    Account.create(:name=>'Mant Acometida',:ancestry=>'1/2')
    Account.create(:name=>'Comercial',:ancestry=>'1/3')
    Account.create(:name=>'Gestion de Impagados',:ancestry=>'1/3')
    Account.create(:name=>'Gestion de Perdidas',:ancestry=>'1/3')
    Account.create(:name=>'Mant Acometida',:ancestry=>'1/3')
    Account.create(:name=>'Comercial',:ancestry=>'1/4')
    Account.create(:name=>'Gestion de Impagados',:ancestry=>'1/4')
    Account.create(:name=>'Gestion de Perdidas',:ancestry=>'1/4')
    Account.create(:name=>'Mant Acometida',:ancestry=>'1/4')
    Account.create(:name=>'Inspeccion de factibilidad y conexion NNSS',:ancestry=>'1/2/5')
    Account.create(:name=>'Muestreo estadistico de lecturas',:ancestry=>'1/2/5')
    Account.create(:name=>'Provisorios',:ancestry=>'1/2/5')
    Account.create(:name=>'Recategorizaciones de T1 a T2',:ancestry=>'1/2/5')
    Account.create(:name=>'Reclamos comerciales',:ancestry=>'1/2/5')
    Account.create(:name=>'Relevamiento AP Cons Calculado',:ancestry=>'1/2/5')
    Account.create(:name=>'Levantamientos por impago',:ancestry=>'1/2/6')
    Account.create(:name=>'Rehabilitaciones',:ancestry=>'1/2/6')
    Account.create(:name=>'Suspensiones',:ancestry=>'1/2/6')
    Account.create(:name=>'Incorporacion de clientes clandestinos o bajo med comunitarios',:ancestry=>'1/2/7')
    Account.create(:name=>'Inspeccion y normalizacion sum peq demandas',:ancestry=>'1/2/7')
    Account.create(:name=>'Reemplazo de red actual clientes con fraude cronico',:ancestry=>'1/2/7')
    Account.create(:name=>'Revision de consumos 0',:ancestry=>'1/2/7')
    Account.create(:name=>'Revision de suministros detectando fraude',:ancestry=>'1/2/7')
    Account.create(:name=>'Revision suministros 10kW < P <=50kW',:ancestry=>'1/2/7')
    Account.create(:name=>'Revision suministros P > 50kW',:ancestry=>'1/2/7')
    Account.create(:name=>'Cambios de medidor',:ancestry=>'1/2/8')
    Account.create(:name=>'Cambios de medidor (antiguos; Monof)',:ancestry=>'1/2/8')
    Account.create(:name=>'Cambios de medidor (antiguos; Trif)',:ancestry=>'1/2/8')
    Account.create(:name=>'Colocacion de tapas de policarbonato',:ancestry=>'1/2/8')
    Account.create(:name=>'Contraste de medidores trifasicos T1',:ancestry=>'1/2/8')
    Account.create(:name=>'Normalizacion de Gabinetes de Edificio',:ancestry=>'1/2/8')
    Account.create(:name=>'Normalizacion equipos de medicion',:ancestry=>'1/2/8')
    Account.create(:name=>'Normalizacion Gabinetes AP',:ancestry=>'1/2/8')
    Account.create(:name=>'Reemplazo de acometidas por concentrico',:ancestry=>'1/2/8')
    Account.create(:name=>'Relevamiento y contraste medidor AP',:ancestry=>'1/2/8')
    Account.create(:name=>'Inspeccion de factibilidad y conexion NNSS',:ancestry=>'1/3/9')
    Account.create(:name=>'Muestreo estadistico de lecturas',:ancestry=>'1/3/9')
    Account.create(:name=>'Provisorios',:ancestry=>'1/3/9')
    Account.create(:name=>'Recategorizaciones de T1 a T2',:ancestry=>'1/3/9')
    Account.create(:name=>'Reclamos comerciales',:ancestry=>'1/3/9')
    Account.create(:name=>'Relevamiento AP Cons Calculado',:ancestry=>'1/3/9')
    Account.create(:name=>'Levantamientos por impago',:ancestry=>'1/3/10')
    Account.create(:name=>'Rehabilitaciones',:ancestry=>'1/3/10')
    Account.create(:name=>'Suspensiones',:ancestry=>'1/3/10')
    Account.create(:name=>'Incorporacion de clientes clandestinos o bajo med comunitarios',:ancestry=>'1/3/11')
    Account.create(:name=>'Inspeccion y normalizacion sum peq demandas',:ancestry=>'1/3/11')
    Account.create(:name=>'Reemplazo de red actual clientes con fraude cronico',:ancestry=>'1/3/11')
    Account.create(:name=>'Revision de consumos 0',:ancestry=>'1/3/11')
    Account.create(:name=>'Revision de suministros detectando fraude',:ancestry=>'1/3/11')
    Account.create(:name=>'Revision suministros 10kW < P <=50kW',:ancestry=>'1/3/11')
    Account.create(:name=>'Revision suministros P > 50kW',:ancestry=>'1/3/11')
    Account.create(:name=>'Cambios de medidor',:ancestry=>'1/3/12')
    Account.create(:name=>'Cambios de medidor (antiguos; Monof)',:ancestry=>'1/3/12')
    Account.create(:name=>'Cambios de medidor (antiguos; Trif)',:ancestry=>'1/3/12')
    Account.create(:name=>'Colocacion de tapas de policarbonato',:ancestry=>'1/3/12')
    Account.create(:name=>'Contraste de medidores trifasicos T1',:ancestry=>'1/3/12')
    Account.create(:name=>'Normalizacion de Gabinetes de Edificio',:ancestry=>'1/3/12')
    Account.create(:name=>'Normalizacion equipos de medicion',:ancestry=>'1/3/12')
    Account.create(:name=>'Normalizacion Gabinetes AP',:ancestry=>'1/3/12')
    Account.create(:name=>'Reemplazo de acometidas por concentrico',:ancestry=>'1/3/12')
    Account.create(:name=>'Relevamiento y contraste medidor AP',:ancestry=>'1/3/12')
    Account.create(:name=>'Inspeccion de factibilidad y conexion NNSS',:ancestry=>'1/4/13')
    Account.create(:name=>'Muestreo estadistico de lecturas',:ancestry=>'1/4/13')
    Account.create(:name=>'Provisorios',:ancestry=>'1/4/13')
    Account.create(:name=>'Recategorizaciones de T1 a T2',:ancestry=>'1/4/13')
    Account.create(:name=>'Reclamos comerciales',:ancestry=>'1/4/13')
    Account.create(:name=>'Relevamiento AP Cons Calculado',:ancestry=>'1/4/13')
    Account.create(:name=>'Levantamientos por impago',:ancestry=>'1/4/14')
    Account.create(:name=>'Rehabilitaciones',:ancestry=>'1/4/14')
    Account.create(:name=>'Suspensiones',:ancestry=>'1/4/14')
    Account.create(:name=>'Incorporacion de clientes clandestinos o bajo med comunitarios',:ancestry=>'1/4/15')
    Account.create(:name=>'Inspeccion y normalizacion sum peq demandas',:ancestry=>'1/4/15')
    Account.create(:name=>'Reemplazo de red actual clientes con fraude cronico',:ancestry=>'1/4/15')
    Account.create(:name=>'Revision de consumos 0',:ancestry=>'1/4/15')
    Account.create(:name=>'Revision de suministros detectando fraude',:ancestry=>'1/4/15')
    Account.create(:name=>'Revision suministros 10kW < P <=50kW',:ancestry=>'1/4/15')
    Account.create(:name=>'Revision suministros P > 50kW',:ancestry=>'1/4/15')
    Account.create(:name=>'Cambios de medidor',:ancestry=>'1/4/16')
    Account.create(:name=>'Cambios de medidor (antiguos; Monof)',:ancestry=>'1/4/16')
    Account.create(:name=>'Cambios de medidor (antiguos; Trif)',:ancestry=>'1/4/16')
    Account.create(:name=>'Colocacion de tapas de policarbonato',:ancestry=>'1/4/16')
    Account.create(:name=>'Contraste de medidores trifasicos T1',:ancestry=>'1/4/16')
    Account.create(:name=>'Normalizacion de Gabinetes de Edificio',:ancestry=>'1/4/16')
    Account.create(:name=>'Normalizacion equipos de medicion',:ancestry=>'1/4/16')
    Account.create(:name=>'Normalizacion Gabinetes AP',:ancestry=>'1/4/16')
    Account.create(:name=>'Reemplazo de acometidas por concentrico',:ancestry=>'1/4/16')
    Account.create(:name=>'Relevamiento y contraste medidor AP',:ancestry=>'1/4/16')
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/5/17',:taverage=>80)
    Account.create(:name=>'Capital',:ancestry=>'1/2/5/17',:taverage=>80)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/5/17',:taverage=>80)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/5/17',:taverage=>80)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/5/17',:taverage=>80)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/5/17',:taverage=>80)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/5/18',:taverage=>0)
    Account.create(:name=>'Capital',:ancestry=>'1/2/5/18',:taverage=>0)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/5/18',:taverage=>0)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/5/18',:taverage=>0)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/5/18',:taverage=>0)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/5/18',:taverage=>0)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/5/19',:taverage=>60)
    Account.create(:name=>'Capital',:ancestry=>'1/2/5/19',:taverage=>60)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/5/19',:taverage=>60)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/5/19',:taverage=>60)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/5/19',:taverage=>60)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/5/19',:taverage=>60)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/5/20',:taverage=>45)
    Account.create(:name=>'Capital',:ancestry=>'1/2/5/20',:taverage=>45)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/5/20',:taverage=>45)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/5/20',:taverage=>45)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/5/20',:taverage=>45)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/5/20',:taverage=>45)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/5/21',:taverage=>50)
    Account.create(:name=>'Capital',:ancestry=>'1/2/5/21',:taverage=>50)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/5/21',:taverage=>50)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/5/21',:taverage=>50)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/5/21',:taverage=>50)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/5/21',:taverage=>50)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/5/22',:taverage=>10560)
    Account.create(:name=>'Capital',:ancestry=>'1/2/5/22',:taverage=>10560)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/5/22',:taverage=>10560)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/6/23',:taverage=>40)
    Account.create(:name=>'Capital',:ancestry=>'1/2/6/23',:taverage=>40)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/6/23',:taverage=>40)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/6/23',:taverage=>40)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/6/23',:taverage=>40)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/6/23',:taverage=>40)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/6/24',:taverage=>20)
    Account.create(:name=>'Capital',:ancestry=>'1/2/6/24',:taverage=>20)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/6/24',:taverage=>20)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/6/24',:taverage=>20)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/6/24',:taverage=>20)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/6/24',:taverage=>20)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/6/25',:taverage=>20)
    Account.create(:name=>'Capital',:ancestry=>'1/2/6/25',:taverage=>20)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/6/25',:taverage=>20)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/6/25',:taverage=>20)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/6/25',:taverage=>20)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/6/25',:taverage=>20)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/7/26',:taverage=>60)
    Account.create(:name=>'Capital',:ancestry=>'1/2/7/26',:taverage=>60)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/7/26',:taverage=>60)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/7/26',:taverage=>60)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/7/26',:taverage=>60)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/7/26',:taverage=>60)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/7/27',:taverage=>3.2)
    Account.create(:name=>'Capital',:ancestry=>'1/2/7/27',:taverage=>3.2)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/7/27',:taverage=>3.2)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/7/27',:taverage=>3.2)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/7/27',:taverage=>3.2)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/7/27',:taverage=>3.2)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/7/28',:taverage=>120)
    Account.create(:name=>'Capital',:ancestry=>'1/2/7/28',:taverage=>120)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/7/28',:taverage=>120)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/7/28',:taverage=>120)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/7/28',:taverage=>120)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/7/28',:taverage=>120)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/7/29',:taverage=>25)
    Account.create(:name=>'Capital',:ancestry=>'1/2/7/29',:taverage=>25)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/7/29',:taverage=>25)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/7/29',:taverage=>25)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/7/29',:taverage=>25)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/7/29',:taverage=>25)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/7/30',:taverage=>3.2)
    Account.create(:name=>'Capital',:ancestry=>'1/2/7/30',:taverage=>3.2)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/7/30',:taverage=>3.2)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/7/30',:taverage=>3.2)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/7/30',:taverage=>3.2)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/7/30',:taverage=>3.2)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/7/31',:taverage=>40)
    Account.create(:name=>'Capital',:ancestry=>'1/2/7/31',:taverage=>40)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/7/31',:taverage=>40)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/7/31',:taverage=>40)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/7/31',:taverage=>40)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/7/31',:taverage=>40)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/7/32',:taverage=>45)
    Account.create(:name=>'Capital',:ancestry=>'1/2/7/32',:taverage=>45)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/7/32',:taverage=>45)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/7/32',:taverage=>45)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/7/32',:taverage=>45)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/7/32',:taverage=>45)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/33',:taverage=>60)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/33',:taverage=>60)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/33',:taverage=>60)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/33',:taverage=>60)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/33',:taverage=>60)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/33',:taverage=>60)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/34',:taverage=>40)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/34',:taverage=>40)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/34',:taverage=>40)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/34',:taverage=>40)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/34',:taverage=>40)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/34',:taverage=>40)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/35',:taverage=>40)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/35',:taverage=>40)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/35',:taverage=>40)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/35',:taverage=>40)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/35',:taverage=>40)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/35',:taverage=>40)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/36',:taverage=>20)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/36',:taverage=>20)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/36',:taverage=>20)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/36',:taverage=>20)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/36',:taverage=>20)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/36',:taverage=>20)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/37',:taverage=>30)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/37',:taverage=>30)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/37',:taverage=>30)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/37',:taverage=>30)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/37',:taverage=>30)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/37',:taverage=>30)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/38',:taverage=>120)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/38',:taverage=>120)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/38',:taverage=>120)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/38',:taverage=>120)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/38',:taverage=>120)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/38',:taverage=>120)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/39',:taverage=>90)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/39',:taverage=>90)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/39',:taverage=>90)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/39',:taverage=>90)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/39',:taverage=>90)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/39',:taverage=>90)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/40',:taverage=>160)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/40',:taverage=>160)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/40',:taverage=>160)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/40',:taverage=>160)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/40',:taverage=>160)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/40',:taverage=>160)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/41',:taverage=>50)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/41',:taverage=>50)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/41',:taverage=>50)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/41',:taverage=>50)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/41',:taverage=>50)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/41',:taverage=>50)
    Account.create(:name=>'Aimogasta',:ancestry=>'1/2/8/42',:taverage=>30)
    Account.create(:name=>'Capital',:ancestry=>'1/2/8/42',:taverage=>30)
    Account.create(:name=>'Chamical',:ancestry=>'1/2/8/42',:taverage=>30)
    Account.create(:name=>'Chepes',:ancestry=>'1/2/8/42',:taverage=>30)
    Account.create(:name=>'Chilecito',:ancestry=>'1/2/8/42',:taverage=>30)
    Account.create(:name=>'Villa Union',:ancestry=>'1/2/8/42',:taverage=>30)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/9/43',:taverage=>80)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/9/43',:taverage=>80)
    Account.create(:name=>'JVG',:ancestry=>'1/3/9/43',:taverage=>80)
    Account.create(:name=>'Metan',:ancestry=>'1/3/9/43',:taverage=>80)
    Account.create(:name=>'Oran',:ancestry=>'1/3/9/43',:taverage=>80)
    Account.create(:name=>'Salta',:ancestry=>'1/3/9/43',:taverage=>80)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/9/43',:taverage=>80)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/9/44',:taverage=>0)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/9/44',:taverage=>0)
    Account.create(:name=>'JVG',:ancestry=>'1/3/9/44',:taverage=>0)
    Account.create(:name=>'Metan',:ancestry=>'1/3/9/44',:taverage=>0)
    Account.create(:name=>'Oran',:ancestry=>'1/3/9/44',:taverage=>0)
    Account.create(:name=>'Salta',:ancestry=>'1/3/9/44',:taverage=>0)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/9/44',:taverage=>0)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/9/45',:taverage=>60)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/9/45',:taverage=>60)
    Account.create(:name=>'JVG',:ancestry=>'1/3/9/45',:taverage=>60)
    Account.create(:name=>'Metan',:ancestry=>'1/3/9/45',:taverage=>60)
    Account.create(:name=>'Oran',:ancestry=>'1/3/9/45',:taverage=>60)
    Account.create(:name=>'Salta',:ancestry=>'1/3/9/45',:taverage=>60)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/9/45',:taverage=>60)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/9/46',:taverage=>45)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/9/46',:taverage=>45)
    Account.create(:name=>'JVG',:ancestry=>'1/3/9/46',:taverage=>45)
    Account.create(:name=>'Metan',:ancestry=>'1/3/9/46',:taverage=>45)
    Account.create(:name=>'Oran',:ancestry=>'1/3/9/46',:taverage=>45)
    Account.create(:name=>'Salta',:ancestry=>'1/3/9/46',:taverage=>45)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/9/46',:taverage=>45)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/9/47',:taverage=>50)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/9/47',:taverage=>50)
    Account.create(:name=>'JVG',:ancestry=>'1/3/9/47',:taverage=>50)
    Account.create(:name=>'Metan',:ancestry=>'1/3/9/47',:taverage=>50)
    Account.create(:name=>'Oran',:ancestry=>'1/3/9/47',:taverage=>50)
    Account.create(:name=>'Salta',:ancestry=>'1/3/9/47',:taverage=>50)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/9/47',:taverage=>50)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/9/48',:taverage=>10560)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/9/48',:taverage=>10560)
    Account.create(:name=>'JVG',:ancestry=>'1/3/9/48',:taverage=>10560)
    Account.create(:name=>'Metan',:ancestry=>'1/3/9/48',:taverage=>10560)
    Account.create(:name=>'Oran',:ancestry=>'1/3/9/48',:taverage=>10560)
    Account.create(:name=>'Salta',:ancestry=>'1/3/9/48',:taverage=>10560)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/9/48',:taverage=>10560)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/10/49',:taverage=>40)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/10/49',:taverage=>40)
    Account.create(:name=>'JVG',:ancestry=>'1/3/10/49',:taverage=>40)
    Account.create(:name=>'Metan',:ancestry=>'1/3/10/49',:taverage=>40)
    Account.create(:name=>'Oran',:ancestry=>'1/3/10/49',:taverage=>40)
    Account.create(:name=>'Salta',:ancestry=>'1/3/10/49',:taverage=>40)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/10/49',:taverage=>40)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/10/50',:taverage=>20)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/10/50',:taverage=>20)
    Account.create(:name=>'JVG',:ancestry=>'1/3/10/50',:taverage=>20)
    Account.create(:name=>'Metan',:ancestry=>'1/3/10/50',:taverage=>20)
    Account.create(:name=>'Oran',:ancestry=>'1/3/10/50',:taverage=>20)
    Account.create(:name=>'Salta',:ancestry=>'1/3/10/50',:taverage=>20)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/10/50',:taverage=>20)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/10/51',:taverage=>20)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/10/51',:taverage=>20)
    Account.create(:name=>'JVG',:ancestry=>'1/3/10/51',:taverage=>20)
    Account.create(:name=>'Metan',:ancestry=>'1/3/10/51',:taverage=>20)
    Account.create(:name=>'Oran',:ancestry=>'1/3/10/51',:taverage=>20)
    Account.create(:name=>'Salta',:ancestry=>'1/3/10/51',:taverage=>20)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/10/51',:taverage=>20)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/11/52',:taverage=>60)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/11/52',:taverage=>60)
    Account.create(:name=>'JVG',:ancestry=>'1/3/11/52',:taverage=>60)
    Account.create(:name=>'Metan',:ancestry=>'1/3/11/52',:taverage=>60)
    Account.create(:name=>'Oran',:ancestry=>'1/3/11/52',:taverage=>60)
    Account.create(:name=>'Salta',:ancestry=>'1/3/11/52',:taverage=>60)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/11/52',:taverage=>60)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/11/53',:taverage=>3.2)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/11/53',:taverage=>3.2)
    Account.create(:name=>'JVG',:ancestry=>'1/3/11/53',:taverage=>3.2)
    Account.create(:name=>'Metan',:ancestry=>'1/3/11/53',:taverage=>3.2)
    Account.create(:name=>'Oran',:ancestry=>'1/3/11/53',:taverage=>3.2)
    Account.create(:name=>'Salta',:ancestry=>'1/3/11/53',:taverage=>3.2)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/11/53',:taverage=>3.2)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/11/54',:taverage=>120)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/11/54',:taverage=>120)
    Account.create(:name=>'JVG',:ancestry=>'1/3/11/54',:taverage=>120)
    Account.create(:name=>'Metan',:ancestry=>'1/3/11/54',:taverage=>120)
    Account.create(:name=>'Oran',:ancestry=>'1/3/11/54',:taverage=>120)
    Account.create(:name=>'Salta',:ancestry=>'1/3/11/54',:taverage=>120)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/11/54',:taverage=>120)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/11/55',:taverage=>25)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/11/55',:taverage=>25)
    Account.create(:name=>'JVG',:ancestry=>'1/3/11/55',:taverage=>25)
    Account.create(:name=>'Metan',:ancestry=>'1/3/11/55',:taverage=>25)
    Account.create(:name=>'Oran',:ancestry=>'1/3/11/55',:taverage=>25)
    Account.create(:name=>'Salta',:ancestry=>'1/3/11/55',:taverage=>25)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/11/55',:taverage=>25)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/11/56',:taverage=>3.2)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/11/56',:taverage=>3.2)
    Account.create(:name=>'JVG',:ancestry=>'1/3/11/56',:taverage=>3.2)
    Account.create(:name=>'Metan',:ancestry=>'1/3/11/56',:taverage=>3.2)
    Account.create(:name=>'Oran',:ancestry=>'1/3/11/56',:taverage=>3.2)
    Account.create(:name=>'Salta',:ancestry=>'1/3/11/56',:taverage=>3.2)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/11/56',:taverage=>3.2)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/11/57',:taverage=>40)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/11/57',:taverage=>40)
    Account.create(:name=>'JVG',:ancestry=>'1/3/11/57',:taverage=>40)
    Account.create(:name=>'Metan',:ancestry=>'1/3/11/57',:taverage=>40)
    Account.create(:name=>'Oran',:ancestry=>'1/3/11/57',:taverage=>40)
    Account.create(:name=>'Salta',:ancestry=>'1/3/11/57',:taverage=>40)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/11/57',:taverage=>40)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/11/58',:taverage=>45)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/11/58',:taverage=>45)
    Account.create(:name=>'JVG',:ancestry=>'1/3/11/58',:taverage=>45)
    Account.create(:name=>'Metan',:ancestry=>'1/3/11/58',:taverage=>45)
    Account.create(:name=>'Oran',:ancestry=>'1/3/11/58',:taverage=>45)
    Account.create(:name=>'Salta',:ancestry=>'1/3/11/58',:taverage=>45)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/11/58',:taverage=>45)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/59',:taverage=>60)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/59',:taverage=>60)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/59',:taverage=>60)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/59',:taverage=>60)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/59',:taverage=>60)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/59',:taverage=>60)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/59',:taverage=>60)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/60',:taverage=>40)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/60',:taverage=>40)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/60',:taverage=>40)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/60',:taverage=>40)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/60',:taverage=>40)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/60',:taverage=>40)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/60',:taverage=>40)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/61',:taverage=>40)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/61',:taverage=>40)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/61',:taverage=>40)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/61',:taverage=>40)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/61',:taverage=>40)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/61',:taverage=>40)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/61',:taverage=>40)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/62',:taverage=>20)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/62',:taverage=>20)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/62',:taverage=>20)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/62',:taverage=>20)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/62',:taverage=>20)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/62',:taverage=>20)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/62',:taverage=>20)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/63',:taverage=>30)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/63',:taverage=>30)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/63',:taverage=>30)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/63',:taverage=>30)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/63',:taverage=>30)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/63',:taverage=>30)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/63',:taverage=>30)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/64',:taverage=>120)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/64',:taverage=>120)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/64',:taverage=>120)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/64',:taverage=>120)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/64',:taverage=>120)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/64',:taverage=>120)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/64',:taverage=>120)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/65',:taverage=>90)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/65',:taverage=>90)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/65',:taverage=>90)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/65',:taverage=>90)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/65',:taverage=>90)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/65',:taverage=>90)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/65',:taverage=>90)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/66',:taverage=>60)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/66',:taverage=>60)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/66',:taverage=>60)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/66',:taverage=>60)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/66',:taverage=>60)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/66',:taverage=>60)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/66',:taverage=>60)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/67',:taverage=>50)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/67',:taverage=>50)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/67',:taverage=>50)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/67',:taverage=>50)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/67',:taverage=>50)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/67',:taverage=>50)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/67',:taverage=>50)
    Account.create(:name=>'Cafayate',:ancestry=>'1/3/12/68',:taverage=>45)
    Account.create(:name=>'Guemes',:ancestry=>'1/3/12/68',:taverage=>45)
    Account.create(:name=>'JVG',:ancestry=>'1/3/12/68',:taverage=>45)
    Account.create(:name=>'Metan',:ancestry=>'1/3/12/68',:taverage=>45)
    Account.create(:name=>'Oran',:ancestry=>'1/3/12/68',:taverage=>45)
    Account.create(:name=>'Salta',:ancestry=>'1/3/12/68',:taverage=>45)
    Account.create(:name=>'Tartagal',:ancestry=>'1/3/12/68',:taverage=>45)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/13/69',:taverage=>80)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/13/69',:taverage=>80)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/13/69',:taverage=>80)
    Account.create(:name=>'Quines',:ancestry=>'1/4/13/69',:taverage=>80)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/13/69',:taverage=>80)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/13/69',:taverage=>80)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/13/70',:taverage=>0)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/13/70',:taverage=>0)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/13/70',:taverage=>0)
    Account.create(:name=>'Quines',:ancestry=>'1/4/13/70',:taverage=>0)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/13/70',:taverage=>0)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/13/70',:taverage=>0)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/13/71',:taverage=>60)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/13/71',:taverage=>60)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/13/71',:taverage=>60)
    Account.create(:name=>'Quines',:ancestry=>'1/4/13/71',:taverage=>60)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/13/71',:taverage=>60)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/13/71',:taverage=>60)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/13/72',:taverage=>45)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/13/72',:taverage=>45)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/13/72',:taverage=>45)
    Account.create(:name=>'Quines',:ancestry=>'1/4/13/72',:taverage=>45)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/13/72',:taverage=>45)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/13/72',:taverage=>45)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/13/73',:taverage=>50)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/13/73',:taverage=>50)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/13/73',:taverage=>50)
    Account.create(:name=>'Quines',:ancestry=>'1/4/13/73',:taverage=>50)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/13/73',:taverage=>50)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/13/73',:taverage=>50)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/13/74',:taverage=>10560)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/13/74',:taverage=>10560)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/13/74',:taverage=>10560)
    Account.create(:name=>'Quines',:ancestry=>'1/4/13/74',:taverage=>10560)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/13/74',:taverage=>10560)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/13/74',:taverage=>10560)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/14/75',:taverage=>40)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/14/75',:taverage=>40)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/14/75',:taverage=>40)
    Account.create(:name=>'Quines',:ancestry=>'1/4/14/75',:taverage=>40)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/14/75',:taverage=>40)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/14/75',:taverage=>40)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/14/76',:taverage=>20)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/14/76',:taverage=>20)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/14/76',:taverage=>20)
    Account.create(:name=>'Quines',:ancestry=>'1/4/14/76',:taverage=>20)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/14/76',:taverage=>20)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/14/76',:taverage=>20)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/14/77',:taverage=>20)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/14/77',:taverage=>20)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/14/77',:taverage=>20)
    Account.create(:name=>'Quines',:ancestry=>'1/4/14/77',:taverage=>20)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/14/77',:taverage=>20)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/14/77',:taverage=>20)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/15/78',:taverage=>60)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/15/78',:taverage=>60)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/15/78',:taverage=>60)
    Account.create(:name=>'Quines',:ancestry=>'1/4/15/78',:taverage=>60)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/15/78',:taverage=>60)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/15/78',:taverage=>60)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/15/79',:taverage=>3.2)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/15/79',:taverage=>3.2)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/15/79',:taverage=>3.2)
    Account.create(:name=>'Quines',:ancestry=>'1/4/15/79',:taverage=>3.2)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/15/79',:taverage=>3.2)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/15/79',:taverage=>3.2)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/15/80',:taverage=>120)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/15/80',:taverage=>120)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/15/80',:taverage=>120)
    Account.create(:name=>'Quines',:ancestry=>'1/4/15/80',:taverage=>120)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/15/80',:taverage=>120)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/15/80',:taverage=>120)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/15/81',:taverage=>25)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/15/81',:taverage=>25)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/15/81',:taverage=>25)
    Account.create(:name=>'Quines',:ancestry=>'1/4/15/81',:taverage=>25)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/15/81',:taverage=>25)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/15/81',:taverage=>25)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/15/82',:taverage=>3.2)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/15/82',:taverage=>3.2)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/15/82',:taverage=>3.2)
    Account.create(:name=>'Quines',:ancestry=>'1/4/15/82',:taverage=>3.2)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/15/82',:taverage=>3.2)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/15/82',:taverage=>3.2)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/15/83',:taverage=>40)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/15/83',:taverage=>40)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/15/83',:taverage=>40)
    Account.create(:name=>'Quines',:ancestry=>'1/4/15/83',:taverage=>40)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/15/83',:taverage=>40)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/15/83',:taverage=>40)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/15/84',:taverage=>45)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/15/84',:taverage=>45)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/15/84',:taverage=>45)
    Account.create(:name=>'Quines',:ancestry=>'1/4/15/84',:taverage=>45)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/15/84',:taverage=>45)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/15/84',:taverage=>45)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/85',:taverage=>60)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/85',:taverage=>60)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/85',:taverage=>60)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/85',:taverage=>60)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/85',:taverage=>60)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/85',:taverage=>60)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/86',:taverage=>40)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/86',:taverage=>40)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/86',:taverage=>40)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/86',:taverage=>40)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/86',:taverage=>40)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/86',:taverage=>40)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/87',:taverage=>40)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/87',:taverage=>40)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/87',:taverage=>40)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/87',:taverage=>40)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/87',:taverage=>40)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/87',:taverage=>40)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/88',:taverage=>20)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/88',:taverage=>20)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/88',:taverage=>20)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/88',:taverage=>20)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/88',:taverage=>20)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/88',:taverage=>20)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/89',:taverage=>30)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/89',:taverage=>30)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/89',:taverage=>30)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/89',:taverage=>30)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/89',:taverage=>30)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/89',:taverage=>30)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/90',:taverage=>120)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/90',:taverage=>120)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/90',:taverage=>120)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/90',:taverage=>120)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/90',:taverage=>120)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/90',:taverage=>120)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/91',:taverage=>90)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/91',:taverage=>90)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/91',:taverage=>90)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/91',:taverage=>90)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/91',:taverage=>90)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/91',:taverage=>90)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/92',:taverage=>60)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/92',:taverage=>60)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/92',:taverage=>60)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/92',:taverage=>60)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/92',:taverage=>60)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/92',:taverage=>60)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/93',:taverage=>50)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/93',:taverage=>50)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/93',:taverage=>50)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/93',:taverage=>50)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/93',:taverage=>50)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/93',:taverage=>50)
    Account.create(:name=>'Fortuna',:ancestry=>'1/4/16/94',:taverage=>45)
    Account.create(:name=>'La Toma',:ancestry=>'1/4/16/94',:taverage=>45)
    Account.create(:name=>'Merlo',:ancestry=>'1/4/16/94',:taverage=>45)
    Account.create(:name=>'Quines',:ancestry=>'1/4/16/94',:taverage=>45)
    Account.create(:name=>'San Luis',:ancestry=>'1/4/16/94',:taverage=>45)
    Account.create(:name=>'V. Mercedes',:ancestry=>'1/4/16/94',:taverage=>45)
    
  end

  def self.down
    drop_table :accounts
  end
end
